//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shedule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScheduleBaseEntities : DbContext
    {
        public ScheduleBaseEntities()
            : base("name=ScheduleBaseEntities")
        {
        }
        private static ScheduleBaseEntities _context;
        public static ScheduleBaseEntities GetContext()
        {
            if (_context == null)
                _context = new ScheduleBaseEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dates> Dates { get; set; }
        public virtual DbSet<Disciplines> Disciplines { get; set; }
        public virtual DbSet<Eventes> Eventes { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<Lessons_types> Lessons_types { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<Week_days> Week_days { get; set; }
    }
}
