//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lessons()
        {
            this.Eventes = new HashSet<Eventes>();
        }
    
        public int Id { get; set; }
        public int Disciplines_Id { get; set; }
        public int Lessons_types_Id { get; set; }
        public int Teachers_Id { get; set; }
        public int Dates_Id { get; set; }
    
        public virtual Dates Dates { get; set; }
        public virtual Disciplines Disciplines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventes> Eventes { get; set; }
        public virtual Lessons_types Lessons_types { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
